export const sharedText = {
  'New item': 'Hàng mới',
  Name: 'Tên',
  Quantity: 'Số lượng',
  Price: 'Giá',
  'Printer ink': 'Mực in',
  Search: 'Tìm',
  Import: 'Nhập',
  Export: 'Xuất',
  Close: 'Đóng',
  Activity: 'Hoạt động',
  'Import price': 'Giá nhập',
  'Export price': 'Giá xuất',
  Time: 'Thời gian',
  Type: 'Loại',
}
